[workspace]
members = [
    "shared",
    "gateway",
    "auth",
    "messaging",
    "presence",
    "encryption-service",
    "moderation",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
